version: '3.2'
services:
  pfelk01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: pfelk01
    restart: unless-stopped
    hostname: pfelk01
    environment:
       - node.name=pfelk01
       - cluster.name=pfelk-docker-cluster
       - discovery.seed_hosts=pfelk02,pfelk03
       - cluster.initial_master_nodes=pfelk01,pfelk02
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
       - pfelk01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - pfelk

  pfelk02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: pfelk02
    restart: unless-stopped
    hostname: pfelk02
    environment:
       - node.name=pfelk02
       - cluster.name=pfelk-docker-cluster
       - discovery.seed_hosts=pfelk01,pfelk03
       - cluster.initial_master_nodes=pfelk01,pfelk02,pfelk03
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
       - pfelk02:/usr/share/elasticsearch/data
    networks:
      - pfelk

  pfelk03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: pfelk03
    restart: unless-stopped
    hostname: pfelk03
    environment:
       - node.name=pfelk03
       - cluster.name=pfelk-docker-cluster
       - discovery.seed_hosts=pfelk01,pfelk02
       - cluster.initial_master_nodes=pfelk01,pfelk02,pfelk03
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
       - pfelk02:/usr/share/elasticsearch/data
    networks:
      - pfelk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/patterns/:/usr/share/logstash/patterns/
      - ./logstash/GeoIP/:/usr/share/logstash/GeoIP/
    ports:
      - "5000:5000"
      - "9600:9600"
      - "5140:5140/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx1G -Xms1G"
    networks:
      - pfelk
#    depends_on:
#      - pfelk01,pfelk02

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - pfelk
    depends_on:
      - logstash

volumes:
  pfelk01:
    driver: local
  pfelk02:
    driver: local
networks:
  pfelk:
    driver: bridge

    # Reference https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
